version: '3.3'

volumes:
  postgres_data:
    driver: local

services:
  kibana:
    image: docker.elastic.co/beats/filebeat:7.17.6
    container_name: filebeat
    # volumes:
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    # ports:
      # - "5601:5601"
