version: '3.3'

volumes:
  postgres_data:
    driver: local

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: kibana
    # volumes:
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "5601:5601"
